### PR TITLE
Fixed/docker

### PR DESCRIPTION
**Pull request by DevNinja5**
1. Fixed Docker-compose to solve IP address problem. Services can now connect by their names.
2. Enabled the profiles in docker-compose to easily deploy senior monitoring services [refer README.md]
3. Added a script to install docker easily
4. Updated the documentation

### CODE REVIEW

**Comment by DevNinja5** [comment]
@qwxingzhe

**Comment by DevNinja5** [comment]
@qwxingzhe  check this PR 
I have made your project simpler and functionalities are same and some fixes is done

**Comment by qwxingzhe** [comment]
@Rahul-Soni28 THX. It's great

**Comment by DevNinja5** [comment]
@qwxingzhe 
Feel free to reach out for more DevOps solutions.

**Pull request merged**
